#!/bin/bash

printf "   ___       __                        __       \n"
printf "  / _ |__ __/ /____  ___  _______ ____/ /__ ____\n"
printf " / __ / // / __/ _ \/ _ \\/ __/ _ \\/ _  / -_) __/\n"
printf "/_/ |_\\_,_/\\__/\\___/\\_, /_/  \\_,_/\\_,_/\\__/_/\n"
printf "                   /___/\n\n"
printf "             Machine Structures\n"
printf "     Great Ideas in Computer Architecture\n\n"

if [ $# -gt 0 ]; then
  if [ "$1" = "simple" ]; then
    bash test/simple.sh
  elif [ "$1" = "huge" ]; then
    bash test/huge.sh
  elif [ "$1" = "speedup" ]; then
    if [ ! -f "optimized" ] || [ ! -f "baseline" ]; then
      echo "Need to run 'make' first!"
      exit 2
    fi
    python3 test/speedup.py
  else
    echo "usage: ./check simple|huge|speedup";
    exit 2
  fi
else
  echo "usage: ./check simple|huge|speedup";
  exit 2
fi
