#!/bin/bash

# download CIFAR-10 dataset
if [ ! -f cifar-10-binary.tar.gz ]; then
  echo "downloading cifar-10-binary.tar.gz..."
  wget -c https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz
else
  echo "cifar-10-binary.tar.gz has already been downloaded..."
fi

# check sum
echo "checking file integrity..."
check=$(md5sum cifar-10-binary.tar.gz | cut -d' ' -f1)
if [ $check != "c32a1d4ab5d03f1284b67883e8d87530" ]; then
  echo "cifar-10-binary.tar.gz is corrupted, try again..."
  rm -f cifar-10-binary.tar.gz
  return 1
else
  echo "cifar-10-binary.tar.gz is OK..."
fi

# untar
if [ ! -d cifar-10-batches-bin ]; then
  echo "decompressing cifar-10-binary.tar.gz..."
  tar xvzf cifar-10-binary.tar.gz
else
  echo "cifar-10-binary.tar.gz is already decompressed"
fi

echo "All done..."
